// automatically generated by build_post_index.js
export default [
  {
    "filePath": "pages/posts/2019-06-14-eyeo-recap-creativity-vulnerability-and-activism.md",
    "urlPath": "/posts/2019-06-14-eyeo-recap-creativity-vulnerability-and-activism",
    "path_name": "/posts/2019-06-14-eyeo-recap-creativity-vulnerability-and-activism",
    "publishDate": "2019-06-14T00:00:00.000Z",
    "title": "Eyeo recap: creativity, vulnerability, and activism",
    "summary": "I'm thinking about when to retreat and when to engage.",
    "date": "2019-06-14",
    "feature": false,
    "published": true,
    "post_type": "post",
    "excerpt": "\nexport let nicole = {full: 'Nicole Aptekar', short: 'Nicole', link: 'https://nicolation.net/', pronouns: ['she', 'her','her', 'hers']}\nexport let nathan = {full: 'Nathan Yau', short: 'Nathan', link: 'https://flowingdata.com/', pronouns: ['he', 'him','his', 'his']}\nexport let...",
    "external_url": false
  }
]
