// automatically generated by build_post_index.js
export default [
  {
    "filePath": "pages/posts/2019-06-23-draft.md",
    "urlPath": "/posts/2019-06-23-draft",
    "path_name": "/posts/2019-06-23-draft",
    "draft": true,
    "publishDate": "2019-06-23T00:00:00.000Z",
    "title": "Letter spirit: a model of creativity",
    "summary": "I'm comparing the model of creativity put forward by Douglas Hofstadter and Gary McGraw in their paper on generating a font style with my design process.",
    "date": "2019-06-23",
    "feature": false,
    "published": true,
    "post_type": "post",
    "excerpt": "\nexport let h = {full: 'Douglas Hofstadter and Gary McGraw', short: 'Hofstadter and McGraw', pronouns: ['they', 'them','their','theirs']}\n\nI'm very interested in exploring how metaphors structure our thinking. I recently got excited about this idea reading Metaphors We Live By...",
    "external_url": false
  },
  {
    "filePath": "pages/posts/2019-06-14-eyeo-recap-creativity-vulnerability-and-activism.md",
    "urlPath": "/posts/2019-06-14-eyeo-recap-creativity-vulnerability-and-activism",
    "path_name": "/posts/2019-06-14-eyeo-recap-creativity-vulnerability-and-activism",
    "draft": false,
    "publishDate": "2019-06-14T00:00:00.000Z",
    "title": "Eyeo recap: creativity, vulnerability, and activism",
    "summary": "I'm thinking about when to retreat and when to engage.",
    "date": "2019-06-14",
    "feature": false,
    "published": true,
    "post_type": "post",
    "excerpt": "\nexport let nicole = {full: 'Nicole Aptekar', short: 'Nicole', link: 'https://nicolation.net/', pronouns: ['she', 'her','her', 'hers']}\nexport let nathan = {full: 'Nathan Yau', short: 'Nathan', link: 'https://flowingdata.com/', pronouns: ['he', 'him','his', 'his']}\nexport let...",
    "external_url": false
  }
]
